#!/bin/bash
# Setup Stripe Coupon & Email Campaign

echo "================================"
echo "StudyMaxx Premium Campaign Setup"
echo "================================"
echo ""

# STEP 1: Create Stripe Coupon
echo "STEP 1: Create a 50% OFF coupon in Stripe"
echo "========================================"
echo ""
echo "1. Go to https://dashboard.stripe.com/coupons"
echo "2. Click 'Create coupon'"
echo "3. Fill in:"
echo "   - Coupon code: SAVE50"
echo "   - Discount type: Percentage"
echo "   - Discount percent: 50"
echo "   - Duration: Once (only first month)"
echo "   - Click 'Create coupon'"
echo ""
echo "✓ Done! This coupon will give 50% off first month only"
echo ""
echo ""

# STEP 2: Get user list from Supabase
echo "STEP 2: Export free users from Supabase"
echo "========================================"
echo ""
echo "1. Go to https://app.supabase.com"
echo "2. Select your StudyMaxx project"
echo "3. Click 'SQL Editor' → 'New query'"
echo "4. Paste this SQL:"
echo ""
echo "   SELECT email FROM users"
echo "   WHERE is_premium = false"
echo "     AND email IS NOT NULL"
echo "     AND email != ''"
echo "     AND created_at >= NOW() - INTERVAL '90 days'"
echo "   ORDER BY updated_at DESC;"
echo ""
echo "5. Click 'Run'"
echo "6. Click 'Download' (top right) → CSV"
echo ""
echo ""

# STEP 3: Prepare emails
echo "STEP 3: Prepare the email script"
echo "================================="
echo ""
echo "1. Open: send-premium-campaign.js"
echo "2. Find the users array (around line 13)"
echo "3. Replace with your emails:"
echo ""
echo "   const users = ["
echo "     { email: 'user1@example.com' },"
echo "     { email: 'user2@example.com' },"
echo "     // ... paste all your emails"
echo "   ];"
echo ""
echo "4. Set your Resend API key:"
echo "   export RESEND_API_KEY=\"re_xxxxx\""
echo ""
echo ""

# STEP 4: Send test
echo "STEP 4: Send test email to yourself"
echo "===================================="
echo ""
echo "1. Run: node send-premium-campaign.js"
echo "2. Check your inbox"
echo "3. Click 'Upgrade to Premium Now'"
echo "4. You should see: $8.99 regular price, $4.49 in checkout"
echo "5. The coupon code SAVE50 should appear automatically"
echo ""
echo ""

# STEP 5: Send for real
echo "STEP 5: Send to all users"
echo "=========================="
echo ""
echo "1. Add ALL user emails to the array"
echo "2. Run: node send-premium-campaign.js"
echo "3. Check Resend dashboard: https://resend.com/emails"
echo "4. Monitor in Stripe dashboard: https://dashboard.stripe.com/customers"
echo ""
echo ""

echo "✅ All set! Your campaign is ready to launch"
