"use client";

import { useTranslation } from "../contexts/SettingsContext";
import ArrowIcon from "../components/icons/ArrowIcon";
import Link from "next/link";

export default function TermsPage() {
  const t = useTranslation();

  return (
    <main className="min-h-screen px-4 py-8" style={{ background: 'var(--background)' }}>
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <Link 
            href="/"
            className="inline-flex items-center gap-2 px-4 py-2 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white font-medium transition-colors rounded-full hover:bg-white/50 dark:hover:bg-gray-800/50"
          >
            <ArrowIcon direction="left" size={16} />
            <span>{t("back")}</span>
          </Link>
        </div>

        {/* Content */}
        <div className="bg-white dark:bg-gray-800 rounded-md shadow-xl p-8 md:p-12" style={{ border: '1px solid var(--border)' }}>
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-6">
            Terms of Service
          </h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 mb-8">
            Last updated: December 23, 2025
          </p>

          <div className="space-y-6 text-gray-700 dark:text-gray-300">
            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing and using StudyMaxx ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                2. Description of Service
              </h2>
              <p className="mb-3">
                StudyMaxx is an AI-powered study tool that helps you:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Generate flashcards from your study materials</li>
                <li>Create quiz questions for self-testing</li>
                <li>Track your learning progress</li>
                <li>Study with interactive flashcards</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                3. Beta Service Disclaimer
              </h2>
              <p>
                StudyMaxx is currently in beta. The Service is provided "as is" without warranties of any kind. We may modify, suspend, or discontinue the Service at any time without notice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                4. User Responsibilities
              </h2>
              <p className="mb-3">
                You agree to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Use the Service only for lawful educational purposes</li>
                <li>Not upload content that infringes on others' intellectual property rights</li>
                <li>Not attempt to reverse engineer, hack, or misuse the Service</li>
                <li>Keep your account credentials secure (if applicable)</li>
                <li>Not share copyrighted materials without permission</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                5. Content Ownership
              </h2>
              <p>
                You retain all rights to the content you upload. By using StudyMaxx, you grant us a limited license to process your content for the purpose of generating flashcards and providing the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                6. AI-Generated Content
              </h2>
              <p>
                Flashcards and quiz questions are generated by AI. While we strive for accuracy, the generated content may contain errors. You are responsible for verifying the accuracy of study materials before using them for exams or assessments.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                7. Limitation of Liability
              </h2>
              <p>
                StudyMaxx and its creators are not liable for any damages arising from your use of the Service, including but not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-3">
                <li>Errors in AI-generated content</li>
                <li>Loss of data</li>
                <li>Academic outcomes</li>
                <li>Service interruptions</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                8. Academic Integrity
              </h2>
              <p>
                StudyMaxx is designed as a study aid. You are responsible for ensuring that your use of the Service complies with your institution's academic integrity policies.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                9. Termination
              </h2>
              <p>
                We reserve the right to suspend or terminate your access to the Service at any time for any reason, including violation of these Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                10. Changes to Terms
              </h2>
              <p>
                We may update these Terms of Service at any time. Continued use of the Service after changes constitutes acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                11. Governing Law
              </h2>
              <p>
                These Terms are governed by the laws of Norway. Any disputes shall be resolved in Norwegian courts.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
                12. Contact
              </h2>
              <p>
                For questions about these Terms, contact us at{" "}
                <a href="mailto:studymaxxer@gmail.com" className="text-blue-600 dark:text-blue-400 hover:underline">
                  studymaxxer@gmail.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}
